// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvtibfojwqzfgwroltiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2dGliZm9qd3F6Zmd3cm9sdGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODI5NjYsImV4cCI6MjA2NzQ1ODk2Nn0.G9dwCM-SBZGXhpMVCwWloydE4_kprXj9t69SCEw-Q98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});